export const actionTypes = [
    "FETCH_PRODUCTS",
    "FETCH_PRODUCTS_SUCCESS",
    "FETCH_PRODUCTS_FAIL",
    "FETCH_CATEGORIES",
    "FETCH_CATEGORIES_SUCCESS",
    "FETCH_CATEGORIES_FAIL",
    "SET_CATEGORIES",
];
